site_name: ASTRA

repo_url: https://github.com/andreabellome/astra
repo_name: ASTRA repository

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - js/katex.js # We'll create this next

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Installation: install.md
  - Tutorials:
      - Trips to Jupiter: trips_to_jupiter.md
      - Adding Deep-Space Manoeuvres: deep_space_man.md
      - Low-thrust trajectories: low_thrust_trajectories.md
      - Using NASA ephemerides: nasa_ephemerides.md
      - Using custom input parameters: custom_input.md
  # - API Reference:
  #     - Overview: api_reference.md
  #     - API 1: api1.md
